### PR TITLE
Revert "Added Syntax Highlighting to Code Editors in code-editor"

### PR DESCRIPTION
**Pull request by karanBRAVO**
Reverts karanBRAVO/Code-Editor#1
Not up to the mark.

### CODE REVIEW

**Comment by bethropolis** [comment]
So no syntax highlighting

**Comment by bethropolis** [comment]
What could be the issue?

**Comment by karanBRAVO** [comment]
You have done it correctly but it changes my other other design logic.

**Comment by bethropolis** [comment]
> You have done it correctly but it changes my other design logic.
> 

Ooh, sorry

If you don't mind i will continue to work on the fork i made. This project is amazing.

**Comment by karanBRAVO** [comment]
Ok I will add issue a moment later then you can do it.
I have added more stuff to repo check that also I have added button to change color like notepad and syntax highlighting
If syntax highlighting button is clicked then synta is highlighted

**Comment by bethropolis** [comment]
I can't see the syntax highlighting nor the button

**Comment by karanBRAVO** [comment]
actually I forgot to push it.
### Now Check it
I have added the code and created the issue

**Comment by bethropolis** [comment]
Hey, can you launch a github pages for the project? 

It will really help to keep track of the project.

**Pull request merged**
